# Generated by Django 2.0.1 on 2018-01-24 04:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('broadcasts', '0001_initial'),
        ('unit_prices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=20)),
                ('sign_date', models.DateField()),
                ('contract_type', models.CharField(choices=[('Khai Thác', 'Khai Thác'), ('Tiếp Phát', 'Tiếp Phát')], default='Khai Thác', max_length=10)),
                ('tax', models.FloatField(choices=[(5, 5), (10, 10), (5.0, 5.0), (10.0, 10.0), (5.0, 5.0), (10.0, 10.0)], default=10, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('cancel_date', models.DateField(blank=True, null=True)),
                ('broadcast', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='broadcasts.Broadcast')),
                ('unit_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit_prices.UnitPrice')),
            ],
            options={
                'db_table': 'contracts',
            },
        ),
    ]
